#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /sbin/mailsrvd`

case "$1" in
  start)
    stat_busy "Starting mailsrvd"
    
    if [ -z "$PID" ]; then 
       /sbin/mailsrvd &
    fi
    if [ ! -z "$PID" -o $? -gt 0 ]; then
      stat_fail
    else
      add_daemon mailsrvd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping mailsrvd"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon mailsrvd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
